sudo: required
language: node_js
node_js:
  - "10"

cache:
  directories:   
    - $HOME/.npm
    - node_modules
    
before_install:
  - nvm install 'lts/*'
  - npm i -g npm
  
install:
  - npm install --no-audit --no-progress --quiet
  - npm run pack
  
addons:
    apt:
        packages:
            - sshpass
            
after_success: 
  - shopt -s extglob
  - mkdir build
  - mv dist/* build
  - tar -czf package.tgz build
  - sshpass -p $DEPLOY_PASSWORD scp -o stricthostkeychecking=no -P $DEPLOY_PORT package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -p $DEPLOY_PASSWORD ssh -o stricthostkeychecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh

